// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AgentIO.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/TTransportUtils.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class AgentIOHandler : virtual public AgentIOIf {
 public:
  AgentIOHandler() {
    // Your initialization goes here
  }

  void SendRequest(Response& _return, const Request& req) {
    // Your implementation goes here
    _return.status_code = 0;
    _return.status = "OK";
    _return.body = req.path.c_str();
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AgentIOHandler> handler(new AgentIOHandler());
  shared_ptr<TProcessor> processor(new AgentIOProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TFramedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

